"""empty message

Revision ID: 95ef07151291
Revises: 
Create Date: 2020-10-03 04:41:58.773696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ef07151291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('address_line_1', sa.String(length=500), nullable=False),
    sa.Column('address_line_2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('preferred_currency', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.Column('co_customer_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('co_customer_id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('rewards', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('co_customer_id', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['co_customer_id'], ['customer.co_customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('customer')
    # ### end Alembic commands ###
